### ISSUE TITLE
[ENHANCEMENT] Add option to disable metrics

### ISSUE THREAD

**Issue by cmeschin** [PureStorage-OpenConnect/nagios-plugins#1]
Hi,

Is it possible to add an option to disable metrics like "--no-perfdata" for example?

thanks.
Regards.

**Comment by genegr** [comment]
It is quite likely doable. Let me check what can be done with subclassing the nagiosplugin classes. Also I have moved the plugins into their own project here https://github.com/PureStorage-OpenConnect/nagios-plugins, so for any further bug or enhancement that is the proper place to look for.

Best
