### ISSUE TITLE
syntax errors in various functions

### ISSUE THREAD

**Issue by sylekta** [PureStorage-OpenConnect/nagios-plugins#11]
`raise nagiosplugin.CheckError(f'FA REST call returned "{e}"')
`
Rogue f in there after the open bracket? seems to be in all of the scripts. Script seems to work fine if I remove it

Edit: Seems to be in other functions too
`nagiosplugin.Metric(f'{self.component} hardware is OK' + ' status', 0, context='default' )
`

**Comment by sdodsley** [comment]
f-strings are defined from Python 3.6. Prior to this the code will fail with a syntax error.
