### ISSUE TITLE
check_purefa_hw.py will report OK  for any CTXX

### ISSUE THREAD

**Issue by atmarosi** [PureStorage-OpenConnect/nagios-plugins#2]
My X70 has two controllers; however I can ask for status for CT2 through CT99 and they all report OK:

[XXXXXX@nagios libexec]# ./check_purefa_hw.py XXX.XXX.XXX.15 XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX CT99
PURE_FA_CT99 OK - CT99 status is 0 | 'CT99 status'=0;;@1:1
[XXXXXX@nagios libexec]#./check_purefa_hw.py XXX.XXX.XXX.15 XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX CT0
PURE_FA_CT0 OK - CT0 status is 0 | 'CT0 status'=0;;@1:1

**Comment by PureGabor** [comment]
The newest version handels this issue.
`python3 check_purefa_hw.py XXX.XXX.XXX.XX9 XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX CT3
PURE_FA_HW_CT3 UNKNOWN - no check results
resource PURE_FA_HW_CT3 did not produce any metric`

**Comment by atmarosi** [comment]
I don't see an updated version yet available:
Latest commit 391b785 on Mar 2, 2020
nagios-plugins/check_purefa_hw.py

**Comment by PureGabor** [comment]
The latest commit 391b785 on Mar 2, 2020 contains the fix.

**Comment by atmarosi** [comment]
Checked it out - now i'm getting this:

PURE_FA_ALERTS UNKNOWN - no check results
resource PURE_FA_ALERTS did not produce any metric

**Comment by akhilsambasivan** [comment]
@genegr Will you be able to help on this. I'm also getting the similar error
==
python check_purefa_hw.py -v XX.XX.XX,XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX CH0.BAY0

result
PURE_FA_HW_CH0.BAY0 UNKNOWN - no check results
resource PURE_FA_HW_CH0.BAY0 did not produce any metric
==

For instance, the only script working for me is check_purefa_alert.py and the rest is giving the above while I run it.
